
#Install packages
- hosts: all
  become: yes
  tasks:
    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Install a list of packages
      yum:
        name: "{{ packages }}"
        update_cache: yes
      vars:
        packages:
        - unzip
        - perl
        - vim-enhanced
        - nfs-utils
        - docker-ce 
        - docker-ce-cli 
        - containerd.io

    - name: remove the firewalld package  
      yum:  
        name: firewalld 
        state: absent

    - name: remove packer symbolic link
      file:
        state: absent
        path: "/usr/sbin/packer"

    - name: download packer
      get_url:
        url: "http://192.168.1.30:8000/bin/packer"
        dest: /usr/local/bin/packer
        owner: buildkite-agent
        group: buildkite-agent
        mode: 0775

    - name: download terraform
      get_url:
        url: "http://192.168.1.30:8000/bin/terraform"
        dest: /usr/local/bin/terraform
        owner: buildkite-agent
        group: buildkite-agent
        mode: 0775

    - name: download docker-compose
      get_url:
        url: "http://192.168.1.30:8000/bin/docker-compose"
        dest: /usr/local/bin/docker-compose
        owner: buildkite-agent
        group: buildkite-agent
        mode: 0775

    - name: Download rke
      get_url:
        url: https://github.com/rancher/rke/releases/download/v1.1.2/rke_linux-amd64
        dest: /usr/local/bin/rke
        owner: buildkite-agent
        group: buildkite-agent
        mode: '0775'

    - name: mount nfs:/nfs-drive-1
      mount:
        path: /mnt/nfs-drive-1
        src: 192.168.1.30:/nfs-drive-1
        opts: rw
        state: mounted
        fstype: nfs

    - name: Make buildkite-agent own /mnt/nfs-drive-1
      file:
        path: /mnt/nfs-drive-1
        state: directory
        recurse: yes
        owner: buildkite-agent
        group: buildkite-agent

    - name: Start service docker, if not started
      service:
        name: docker
        state: started
        enabled: yes

    - name: Append the user 'emario' to "docker" group
      user:
        name: emario
        groups: docker
        append: yes

    - name: Append the user 'buildkite-agent' to "docker" group
      user:
        name: buildkite-agent
        groups: docker
        append: yes


